### ISSUE TITLE
[Question] Private Github Dependency doesn't work

### ISSUE THREAD

**Issue by NiklasWagner** [renovatebot/config-help#214] opened 2019-04-23 10:53 UTC
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant
```
INFO: Branch needs creating(dependencies=[], branch="renovate/lock-file-maintenance")
INFO: lock file error(dependencies=[], branch="renovate/lock-file-maintenance")
{
  "cmd": "node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js",
  "args": "install --package-lock-only --no-audit",
  "err": {
    "name": "ChildProcessError",
    "code": 1,
    "childProcess": {},
    "stdout": "",
    "stderr": "npm ERR! Error while executing:\nnpm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/xxxx/nodejs-tools.git\nnpm ERR! \nnpm ERR! ERROR: Repository not found.\nnpm ERR! fatal: Could not read from remote repository.\nnpm ERR! \nnpm ERR! Please make sure you have the correct access rights\nnpm ERR! and the repository exists.\nnpm ERR! \nnpm ERR! exited with error code: 128\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/2019-04-23T10_18_03_523Z-debug.log\n",
    "message": "Command failed: node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\nnpm ERR! Error while executing:\nnpm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/xxx/nodejs-tools.git\nnpm ERR! \nnpm ERR! ERROR: Repository not found.\nnpm ERR! fatal: Could not read from remote repository.\nnpm ERR! \nnpm ERR! Please make sure you have the correct access rights\nnpm ERR! and the repository exists.\nnpm ERR! \nnpm ERR! exited with error code: 128\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/2019-04-23T10_18_03_523Z-debug.log\n `node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit` (exited with error code 1)",
    "stack": "ChildProcessError: Command failed: node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit\nnpm ERR! Error while executing:\nnpm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/xxx/nodejs-tools.git\nnpm ERR! \nnpm ERR! ERROR: Repository not found.\nnpm ERR! fatal: Could not read from remote repository.\nnpm ERR! \nnpm ERR! Please make sure you have the correct access rights\nnpm ERR! and the repository exists.\nnpm ERR! \nnpm ERR! exited with error code: 128\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/2019-04-23T10_18_03_523Z-debug.log\n `node /home/ubuntu/renovateapp/node_modules/npm/bin/npm-cli.js install --package-lock-only --no-audit` (exited with error code 1)\n    at callback (/home/ubuntu/renovateapp/node_modules/child-process-promise/lib/index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:182:13)\n    at ChildProcess.EventEmitter.emit (domain.js:441:20)\n    at maybeClose (internal/child_process.js:962:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)"
  },
  "type": "npm"
}
```
### What is your question?

Hi, we have 2 Repositories and one depends on the other. In our package.json from the Repository we have the following dependency:
```
  "devDependencies": {
    "@xxx/nodejs-tools": "github:xxx/nodejs-tools",
  }
```

It looks like that Renovate can't access our nodejs-tools Repository which isn't true since renovate created a _Configure Renovate_ PR in that Repo as well.

It also looks like that Renovate doesn't pin this dependency to either the Git Hash or to a SemVer Version:
`"@xxx/nodejs-tools": "github:xxx/nodejs-tools#25b2c0ee210bf931947bfcffc2b785711bfc71ec"` or
`"@xxx/nodejs-tools": "github:xxx/nodejs-tools#semver:1.7.0"`

**Comment by rarkins** [comment] 2019-04-23 11:18
@NiklasWagner this is a known issue, I think there is one possible workaround to get it to work. You're right that first of all Renovate needs permission to access the other repository, which you have. The next part is that Renovate needs to pass on the permissions to npm, which itself may pass them on to git. The problem is that git prefers to use SSH authentication, and Renovate's authentication method for GitHub is a token, which does not work for git over ssh.

Anyway, can you see if rewriting the reference to the following works? You will need to request a rebase/retry of PRs after you change config.

```
  "devDependencies": {
    "@xxx/nodejs-tools": "git+https://github.com/xxx/nodejs-tools",
  }
```

The key part is the `git+https://github.com/` part. This lets us search/replace the token within the `package.json` and `package-lock.json` and ensures git can try `https` too. Of course, please verify that it works locally for you first too.

**Comment by NiklasWagner** [comment] 2019-04-23 11:38
Hi @rarkins thanks for answering so quickly.

Switching to git+https helped a bit but raised some more issues:
Renovate created a PR to Pin the dependencys right after pushing this changes so it seems to work now but using git+https breaks our local installation. Most of us use SSH locally so the https method doesn't work when running `npm install`.

Maybe a possible workaround would be if you could check if a strings starts with `github:` and rewrite it to `git+https` but I think you'll have undo this change in the lockfile.

**Comment by rarkins** [comment] 2019-04-23 12:15
@NiklasWagner yes, what you suggest is possible, but requires more "risky" rewriting of both package.json as well as the lock file. I will close this issue it is unfortunately not solvable via config. Instead please track here: https://github.com/renovatebot/renovate/issues/3580

**Closed by rarkins** 2019-04-23 12:15 UTC

**Comment by Illyism** [comment] 2019-07-03 11:18
Is there any way to instruct renovate to ignore this package in the meantime?

**Comment by rarkins** [comment] 2019-07-03 11:23
`ignoreDeps` will tell Renovate to not look them up and warnings will go away for that. 

Npm or yarn lock file updates should normally still succeed because npm and yarn usually don’t attempt to look up/retrieve packages unless they are being updated.

Ultimately the most reliable approach is to give Renovate the credential it needs to look up all packages though.

**Comment by Illyism** [comment] 2019-07-04 08:20
@rarkins It does not seem to solve the issue.

```
npm WARN tar ENOENT: no such file or directory, lstat '/mnt/renovate/gh/officient/officient-core/node_modules/.staging/mark.js-f942a8d8/test/specs'
npm WARN tar ENOENT: no such file or directory, lstat '/mnt/renovate/gh/officient/officient-core/node_modules/.staging/mark.js-f942a8d8/test/specs'
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/Officient/vue-components.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

The package is added as such in package.json

```
"officient-vue-components": "github:Officient/vue-components#v2.1.2",
```

Renovate App has access to the repo.

I've added ignoreDeps as such:

```
"ignoreDeps": [
    "officient-vue-components",
    "github:Officient/vue-components",
    "vue-components"
  ]
```

As noted in this thread, I could change the line to

````
    "officient-vue-components": "git+https://github.com/officient/vue-components#v2.1.2",
```

But that causes issues locally, as our team is authenticated with HTTPS

```
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t https://github.com/officient/vue-components.git
npm ERR! 
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/officient/vue-components.git/'
```

Any suggestions? The npm / shrinkwrap issue is happening on every pull request, causing our CI to always be green, as the shrinkwrap is not updated.

**Comment by rarkins** [comment] 2019-07-04 08:54
Can you open a new issue including as many relevant logs as possible from your setup?
