### ISSUE TITLE
[Question] renovate cannot find my preset

### ISSUE THREAD

**Issue by njzjz** [renovatebot/config-help#207] opened 2019-04-14 07:08 UTC
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

```
INFO: Renovating repository
DEBUG: Using localDir: /mnt/renovate/gh/njzjz/njzjz.github.io
DEBUG: initRepo("njzjz/njzjz.github.io")
DEBUG: Setting hostRule
{
  "config": {
    "name": "GitHub",
    "endpoint": "https://api.github.com/",
    "platform": "github",
    "username": null,
    "password": null,
    "token": "***********",
    "default": true
  }
}
INFO: Authenticated as user: renovate[bot]
INFO: Using renovate version: 15.14.0
DEBUG: njzjz/njzjz.github.io owner = njzjz
DEBUG: njzjz/njzjz.github.io default branch = hexo
DEBUG: Enabling Git FS
INFO: Initialising git repository into /mnt/renovate/gh/njzjz/njzjz.github.io
INFO: git clone completed
{
  "cloneSeconds": 1
}
DEBUG: latest commit
{
  "latestCommitDate": "2019-04-13 21:17:23 +0800"
}
DEBUG: Git private key configured, but not being set
INFO: Setting git author
{
  "gitAuthor": {
    "name": "Renovate Bot",
    "email": "bot@renovateapp.com"
  }
}
DEBUG: resetMemCache()
DEBUG: checkOnboarding()
DEBUG: isOnboarded()
DEBUG: findFile(renovate.json)
DEBUG: config file exists
DEBUG: ensureIssueClosing()
DEBUG: Retrieving issueList
DEBUG: Retrieved 0 issues
DEBUG: Repo is onboarded
DEBUG: Found renovate.json config file
INFO: Repository config
{
  "configFile": "renovate.json",
  "config": {
    "extends": [
      "config:base",
      "github>njzjz/renovate-config"
    ]
  }
}
DEBUG: migrateAndValidate()
DEBUG: No config migration necessary
DEBUG: massaged config
{
  "config": {
    "extends": [
      "config:base",
      "github>njzjz/renovate-config"
    ]
  }
}
DEBUG: migrated config
{
  "config": {
    "extends": [
      "config:base",
      "github>njzjz/renovate-config"
    ]
  }
}
DEBUG: Applying Bearer authentication for host api.github.com
DEBUG: Failed to retrieve default.json from repo
INFO: default.json preset not found - trying renovate.json
DEBUG: Applying Bearer authentication for host api.github.com
DEBUG: Failed to retrieve renovate.json from repo
INFO: Throwing preset error
INFO: Repository has invalid config
{
  "error": {
    "validationError": "Cannot find preset's package (github>njzjz/renovate-config)"
  }
}
DEBUG: raiseConfigWarningIssue()
DEBUG: getBranchPr(renovate/configure)
DEBUG: findPr(renovate/configure, null, open)
DEBUG: Retrieving PR list
DEBUG: Retrieved 26 Pull Requests
DEBUG: ensureIssue()
INFO: Issue created
WARN: Config Warning
{
  "configError": {
    "validationError": "Cannot find preset's package (github>njzjz/renovate-config)"
  },
  "res": "created"
}
INFO: Request stats
{
  "rateLimit": 6400,
  "requestCount": 4,
  "rateLimitRemaining": 6336
}
DEBUG: All requests
{
  "requests": [
    "GET repos/njzjz/njzjz.github.io",
    "GET repos/njzjz/njzjz.github.io/issues?creator=renovate[bot]&state=all&per_page=100&sort=created&direction=asc",
    "GET repos/njzjz/njzjz.github.io/pulls?per_page=100&state=all",
    "POST repos/njzjz/njzjz.github.io/issues"
  ]
}
INFO: Finished repository
```

### What is your question?
Renovate opened an issue (njzjz/njzjz.github.io#115) and commented `Error type: Cannot find preset's package (github>njzjz/renovate-config)`. But in fact, renovate.json has existed in the GitHub repository [njzjz/renovate-config](https://github.com/njzjz/renovate-config).

**Comment by rarkins** [comment] 2019-04-14 07:39
@njzjz I think you have set things up correctly. When I run on your repo locally then Renovate detects your `renovate.json`. I suspect that the problem is isolated to when running app mode, because GitHub wants the app to use a special app `accept` header, so I have pushed this fix to master and will deploy it to the app soon after.

**Comment by rarkins** [comment] 2019-04-14 07:56
Now I'm confused. The Bot closed it all on its own, but right around the time I was fixing it.

**Closed by rarkins** 2019-04-14 07:56 UTC

**Comment by njzjz** [comment] 2019-04-14 08:11
I am not sure but it may be an occasional api problem?  Anyway, thank you!

**Comment by rarkins** [comment] 2019-04-14 08:25
It happened just once so yes seems like it was an ephemeral error. I think unfortunately we suppressed the exact error but I'll try to add code to distinguish between temporary/ephemeral and permanent errors.
