### ISSUE TITLE
Mixing private and public hosts depending on packages

### ISSUE THREAD

**Issue by Xendar** [renovatebot/config-help#888] opened 2020-09-28 13:52 UTC
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

Bitbucket Server self-hosted

### Have you checked the logs? Don't forget to include them if relevant

N/A

### What would you like to do?

So currently I am giving a try to Renovate, using a self-hosted model as we have a Bitbucket Server on premise in my company.
So for my Java/Maven project I have a mix of internal dependencies and public/open source dependencies, and I had the idea to be able to fine tune the Renovate configuration in order to look up for internal dependencies (prefixed with `com.mycompany.`) using our Artifactory on premise, and look up for public dependencies with the default configuration (that would go to Maven Central / Github I would suppose)

I didn't find in the documentation for a way to implement this kind of setup, so for now I'm using only the default host and public dependencies, while filtering the internal ones:

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "onboardingConfig": {
    "extends": ["config:base"]
  },
  "java": {
    "packageRules": [
      {
        "packagePatterns": [
          "^com.mycompany."
        ],
        "enabled": false
      }
    ]
  }
}
```

So, is there way to achieve this? If yes, I suppose I would as well need to explicitly declare the hostrules/managers for public dependencies?

Thanks!

**Comment by viceice** [comment] 2020-09-28 13:59
You can use hostrules and package rules to assign custom registry urls. So renovate will lookup your internal deps on your internal registry.

The host rule can be used to assign credentials if required.

Search this repo for issues, there should be a lot of samples.

**Comment by Xendar** [comment] 2020-09-28 14:06
> 
> 
> You can use hostrules and package rules to assign custom registry urls. So renovate will lookup your internal deps on your internal registry.
> 
> The host rule can be used to assign credentials if required.
> 
> Search this repo for issues, there should be a lot of samples.

Oh maybe I did not use the right keywords, I didn't thought of `registryUrls` I thought it was something for NPM only :D

**Comment by Xendar** [comment] 2020-09-28 21:50
> You can use hostrules and package rules to assign custom registry urls. So renovate will lookup your internal deps on your internal registry.

So if I define a package rule using a custom registry URL, does it exclude the package automatically from the other rules?

**Comment by rarkins** [comment] 2020-09-29 06:08
Duplicate of #892

**Closed by rarkins** 2020-09-29 06:08 UTC
