### ISSUE TITLE
Why did pullrequest automerged?

### ISSUE THREAD

**Issue by scrtree** [renovatebot/config-help#147] opened 2019-01-25 04:10 UTC
### Which Renovate are you using? CLI, App, or Pro
Pro

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### Have you checked the logs? Don't forget to include them if relevant

- log1

```
DEBUG: migrated config
{
  "config": {
    "extends": [
      "config:base"
    ],
    "npm": {
      "packageRules": [
        {
          "automerge": false,
          "packageNames": [
            "jquery-migrate"
          ]
        },
      "patch": {
        "automerge": true,
        "unpublishSafe": true
      }
    }
  }
}
```

- log2

```
DEBUG: Checking #11728 for automerge(dependencies=["jquery-migrate"], branch="renovate/jquery-migrate-3.0.x")
{
  "automerge": true,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
```

- log3

```
DEBUG: mergePr(dependencies=["jquery-migrate"], branch="renovate/jquery-migrate-3.0.x")
{
  "options": {
    "body": {
      "merge_method": "rebase"
    }
  },
  "url": "myrepos/pulls/11728/merge"
}
DEBUG: PR merged(dependencies=["jquery-migrate"], branch="renovate/jquery-migrate-3.0.x")
{
  "pr": 11728
}
INFO: PR automerged(dependencies=["jquery-migrate"], branch="renovate/jquery-migrate-3.0.x")
{
  "pr": 11728
}
```

### What is your question?

Why did "jquery-migrate" automerged?

Best Regards.

**Comment by rarkins** [comment] 2019-01-25 04:59
Hi, which version of Renovate Pro are you running?

**Comment by scrtree** [comment] 2019-01-25 05:32
Hi, I'm using this version.

```
INFO: Authenticated as user: renovate[bot]
INFO: Using renovate version: 14.3.2
```

**Comment by rarkins** [comment] 2019-01-25 05:55
OK, that's not Renovate Pro, that's actually the Renovate App. It looks like you are on the latest version.

The patch rule you have is being evaluated after the jquery-migrate rule. Please post your *original* config here so I can have a look. The migrated config you posted might be not exactly the same as your original.

**Comment by rarkins** [comment] 2019-01-25 07:18
```json
{
  "extends": [
    "config:base"
  ],
  "npm": {
    "separateMinorPatch": true,
    "packageRules": [
      {
		"updateTypes": ["patch"],
        "automerge": true,
        "unpublishSafe": true
      },
      {
        "automerge": false,
        "packageNames": ["jquery-migrate", "prettier", "vue", "vue-template-compiler"]
      },
      {
        "groupName": "vue packages",
        "packageNames": [
          "vue",
          "vue-template-compiler"
        ]
      }
    ]
  }
}
```

Because you want the packageNames rule to override the patch rule, you need to write them both as packageRules and put the packageNames rule after the patch rule so that they are evaluated in the order you intend. Otherwise, rules for major/minor/patch are always evaluated last. Also, add `separateMinorPatch` explicitly so that Renovate knows you want separate PRs for minor and patch updates if both exist.

**Comment by scrtree** [comment] 2019-01-25 07:30
Thanks @rarkins!
I will try what you taught me.

**Comment by rarkins** [comment] 2019-01-25 07:33
You're welcome. Please reopen if the problem persists

**Comment by scrtree** [comment] 2019-02-04 07:15
@rarkins
OK, I’ll give it a try!

**Comment by scrtree** [comment] 2019-02-12 01:42
Hi, @rarkins 
One week has passed, but I don't know the interval of automerge.
Can I think that the issue has been solved?

**Comment by rarkins** [comment] 2019-02-12 09:25
The only way to be sure is if you get an update for any of `"jquery-migrate", "prettier", "vue", "vue-template-compiler"` and they don't automerge. Let's close this and you can request to reopen if one day you find it's not functioning as intended

**Closed by rarkins** 2019-02-12 09:25 UTC
Labels: needs-requirements

**Comment by scrtree** [comment] 2019-02-12 10:40
@rarkins 
I got it.
Thank you for teaching me so patiently!
