### ISSUE TITLE
Failing during artifact creation for private repos.

### ISSUE THREAD

**Issue by dethtron5000** [renovatebot/config-help#527] opened 2020-02-12 20:44 UTC
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?

GitHub Enterprise

### Have you checked the logs? Don't forget to include them if relevant
We are seeing the following during artifact creation:

```
Command failed: docker run --rm -v "/mnt/renovate/gh/nbcnews/frs":"/mnt/renovate/gh/nbcnews/frs" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/renovate-cache/others/go":"/tmp/renovate-cache/others/go" -e GOPATH -e CGO_ENABLED -w "/mnt/renovate/gh/nbcnews/frs" renovate/go bash -l -c "git config --global url.\\\"https://x-access-token:**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./..."
go: github.com/nbcnews/goutils@v0.0.0-20160304172125-8bed90746421: invalid version: git fetch -f https://github.com/nbcnews/goutils refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/renovate-cache/others/go/pkg/mod/cache/vcs/a8a5f807de0b0279565bc2c9e39df1fb359b449089e00be0c9333b07c3fc331f: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled

```

### What would you like to do?
We have several Golang repositories that are failing checks during artifact creation.  They seem to be unable to access some dependencies that are also private repositories.  Renovatebot has access to the private repositories using the same account and seems to be updating them ok, but it's failing when it builds.

Please let us know if you need any additional information.

**Comment by rarkins** [comment] 2020-02-13 05:22
Is this a duplicate of https://github.com/renovatebot/renovate/issues/5459 ?

**Comment by dethtron5000** [comment] 2020-02-13 14:30
Yes - sorry - I got a support email saying to post here.

**Comment by rarkins** [comment] 2020-02-13 14:53
That’s fine, we then transfer issues into the main repo if they look like a bug.

**Closed by rarkins** 2020-02-13 14:53 UTC
